module.exports = [
  { source: 'us.cnn.com', name: 'CNN', view: 'center-left' },
  { source: 'www.cnn.com', name: 'CNN', view: 'center-left' },
  { source: 'github.com', name: 'GitHub', view: 'n/a' },
  { source: 'www.unofficialmysqlguide.com', name: 'The Unofficial MySQL 8.0 Optimizer Guide', view: 'n/a' },
  { source: 'www.abc.net.au', name: 'ABC - Australian Broadcasting Corporation', view: '' },
  { source: 'bigstory.ap.org', name: 'Associated Press - The Big Story', view: 'center' },
  { source: 'www.bbc.co.uk', name: 'BBC', view: 'center-left' },
  { source: 'www.bloomberg.com', name: 'Bloomberg', view: 'center-left' },
  { source: 'www.businessinsider.com', name: 'Business Insider', view: 'center' },
  { source: 'uk.businessinsider.com', name: 'Business Insider UK', view: 'center' },
  { source: 'www.buzzfeed.com', name: 'Buzzfeed', view: 'left' },
  { source: 'www.dailymail.co.uk', name: 'DailyMail', view: 'center-right' },
  { source: 'www.engadget.com', name: 'Engadget', view: 'left' },
  { source: 'ew.com', name: 'Entertainment Weekly', view: 'n/a' },
  { source: 'espn.go.com', name: 'ESPN', view: 'n/a' },
  { source: 'www.espn.com', name: 'ESPN', view: 'n/a' },
  { source: 'www.espnfc.com', name: 'ESPN', view: 'n/a' },
  { source: 'theundefeated.com', name: 'The Undefeated', view: 'n/a' },
  { source: 'www.foxsports.com', name: 'Fox Sports', view: 'n/a' },
  { source: 'www.washingtonpost.com', name: 'The Washington Post', view: 'center-left' },
  { source: 'www.latimes.com', name: 'LA Times', view: '' },
  { source: 'www.newyorker.com', name: 'The New Yorker', view: 'left' },
  { source: 'thehill.com', name: 'The Hill', view: 'right' },
  { source: 'www.chron.com', name: 'Chron - Houston Chronicle', view: 'right' },
  { source: 'techcrunch.com', name: 'Techcrunch', view: 'n/a' },
  { source: 'www.ign.com', name: 'IGN', view: 'n/a' },
  { source: 'www.mirror.co.uk', name: 'Mirror', view: 'center-left'},
  { source: 'mashable.com', name: 'Mashable', view: 'n/a' },
  { source: 'www.mtv.com', name: 'MTV', view: 'left' },
  { source: 'news.nationalgeographic.com', name: 'National Geographic', view: 'center-left' },
  { source: 'www.newscientist.com', name: 'New Scientsit', view: 'n/a'},
  { source: 'www.newsweek.com', name: 'Newsweek', view: 'center-left' },
  { source: 'www.vulture.com', name: 'Vulture', view: 'left' },
  { source: 'nymag.com', name: 'NYMag', view: 'center-left' },
  { source: 'www.nfl.com', name: 'NFL', view: 'n/a' },
  { source: 'www.recode.net', name: 'Recode', view: 'center' },
  { source: 'www.vox.com', name: 'Vox', view: 'left' },
  { source: 'www.theverge.com', name: 'The Verge', view: 'left' },
  { source: 'www.politico.com', name: 'Politico', view: 'center-left' },
  { source: 'www.hollywoodreporter.com', name: 'Hollywood Reporter', view: 'n/a' },
  { source: 'feeds.reuters.com', name: 'Reuters: Top News', view: 'center' },
  { source: 'news.sky.com', name: 'Sky News', view: 'right' },
  { source: 'www.techradar.com', name: 'Techradar', view: 'n/a' },
  { source: 'www.economist.com', name: 'The Economist', view: 'center-right' },
  { source: 'www.theguardian.com', name: 'The Guardian', view: 'center-left' },
  { source: 'www.huffingtonpost.com', name: 'The Huffington Post', view: 'left' },
  { source: 'www.theladbible.com', name: 'The Lad Bible', view: '' },
  { source: 'www.nytimes.com', name: 'The New York Times', view: 'center-left' },
  { source: 'thenextweb.com', name: 'The Next Web', view: 'center-left' },
  { source: 'www.telegraph.co.uk', name: 'Telegraph', view: 'center-left' },
  { source: 'www.wsj.com', name: 'Wall Street Journal', view: 'center' },
  { source: 'time.com', name: 'Time Magazine', view: 'left' },
  { source: 'fortune.com', name: 'Fortune', view: 'center-left' },
  { source: 'www.reddit.com', name: 'Reddit', view: 'n/a' },
  { source: 'rssfeeds.usatoday.com', name: 'USA Today', view: 'center-left' }
  ]